[[redirects]]
  from = "/api"
  to = "https://quill-link-backend-app.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"